import os
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt
import pandas as pd
import textwrap


def add_text_page(pp, title, lines, fontsize=10):
    fig = plt.figure(figsize=(8.27, 11.69))  # A4 in inches
    fig.suptitle(title, fontsize=14)
    left = 0.05
    top = 0.92
    vspace = 0.03
    y = top
    for paragraph in lines:
        wrapped = textwrap.fill(paragraph, width=100)
        fig.text(left, y, wrapped, fontsize=fontsize, va='top')
        y -= vspace * (wrapped.count('\n') + 1)
        if y < 0.05:
            pp.savefig(fig)
            plt.close(fig)
            fig = plt.figure(figsize=(8.27, 11.69))
            y = top
    pp.savefig(fig)
    plt.close(fig)


def add_image_page(pp, img_path, title=None):
    fig = plt.figure(figsize=(8.27, 11.69))
    if title:
        fig.suptitle(title, fontsize=12)
    try:
        img = plt.imread(img_path)
        plt.imshow(img)
        plt.axis('off')
    except Exception as e:
        fig.text(0.1, 0.5, f'Failed to load image {img_path}: {e}', fontsize=12)
    pp.savefig(fig)
    plt.close(fig)


def add_table_page(pp, df, title='Table sample'):
    fig, ax = plt.subplots(figsize=(8.27, 11.69))
    ax.axis('off')
    ax.set_title(title)
    # render first 8 rows and all columns (truncate if many)
    nrows = min(8, len(df))
    table = ax.table(cellText=df.head(nrows).astype(str).values,
                     colLabels=df.columns.tolist(),
                     loc='center', cellLoc='left')
    table.auto_set_font_size(False)
    table.set_fontsize(8)
    table.scale(1, 1.5)
    pp.savefig(fig, bbox_inches='tight')
    plt.close(fig)


def make_report(output_dir='output'):
    os.makedirs(output_dir, exist_ok=True)
    out_pdf = os.path.join(output_dir, 'anomaly_report.pdf')
    labels_md = os.path.join(output_dir, 'cluster_labels.md')
    cluster_png = os.path.join(output_dir, 'anomaly_clusters_pca.png')
    global_png = os.path.join(output_dir, 'pca_scatter.png')
    scores_csv = os.path.join(output_dir, 'anomaly_scores.csv')
    top_csv = os.path.join(output_dir, 'top_anomalies.csv')
    cluster_summary = os.path.join(output_dir, 'cluster_summary.md')

    lines = []
    lines.append('Anomaly Detection Report')
    lines.append('')
    lines.append('This report was generated by src/report.py. It contains cluster labels, PCA visualizations, and example anomalous profiles.')

    with PdfPages(out_pdf) as pp:
        # Title page
        add_text_page(pp, 'Anomaly Detection Report', lines)

        # Add cluster labels
        if os.path.exists(labels_md):
            txt = open(labels_md, 'r', encoding='utf-8').read().splitlines()
            paragraphs = []
            curr = []
            for line in txt:
                if line.strip() == '':
                    if curr:
                        paragraphs.append(' '.join(curr))
                        curr = []
                else:
                    curr.append(line.strip())
            if curr:
                paragraphs.append(' '.join(curr))
            add_text_page(pp, 'Cluster Labels', paragraphs)

        # Add cluster summary md if present
        if os.path.exists(cluster_summary):
            txt = open(cluster_summary, 'r', encoding='utf-8').read()
            add_text_page(pp, 'Cluster Summary', [txt])

        # Add PCA images
        if os.path.exists(global_png):
            add_image_page(pp, global_png, title='Global PCA (anomalies highlighted)')
        if os.path.exists(cluster_png):
            add_image_page(pp, cluster_png, title='Anomalies PCA colored by cluster')

        # Add sample top anomalies table
        if os.path.exists(top_csv):
            df_top = pd.read_csv(top_csv)
            add_table_page(pp, df_top, title='Top anomalous profiles (sample)')

        # Add small footprint of dataset stats
        if os.path.exists(scores_csv):
            df = pd.read_csv(scores_csv)
            stats = [f'Total rows: {len(df)}', f'Anomalies: {df["is_anomaly"].sum()}']
            add_text_page(pp, 'Dataset statistics', stats)

    print(f'Wrote PDF report to {out_pdf}')
    return out_pdf


if __name__ == '__main__':
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument('--out_dir', default='output')
    args = p.parse_args()
    make_report(args.out_dir)
